import React, {useCallback, useEffect, useState} from 'react';
import {ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {ArrowLeft, Edit3, GitBranch, Plus, RefreshCw, Zap} from 'lucide-react-native';
import Toast from 'react-native-toast-message';
import {ApiSession} from '../api/client';
import {getFlowStatus, listFlows} from '../api/flowBuilder';
import {useTheme} from '../theme/theme';

type Props = {projectId: string; session: ApiSession; onBack: () => void; onOpenFlow: (flowId?: string) => void};
export function FlowLibraryScreen({projectId, session, onBack, onOpenFlow}: Props) {
  const theme = useTheme(); const [loading, setLoading] = useState(true); const [flows, setFlows] = useState<any[]>([]); const [activeId, setActiveId] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const [list, status] = await Promise.all([listFlows(session, projectId), getFlowStatus(session, projectId)]); setFlows(Array.isArray(list.data) ? list.data : []); setActiveId(status.active_flow?.flow_id || null); } catch (e) { Toast.show({type: 'error', text1: 'Could not load flows', text2: e instanceof Error ? e.message : undefined}); } finally { setLoading(false); } }, [projectId, session]);
  useEffect(() => { load(); }, [load]); const groups = ['published', 'draft', 'archived'];
  return <View style={[styles.safe, {backgroundColor: theme.canvas}]}><View style={[styles.header, {backgroundColor: theme.header, borderBottomColor: theme.border}]}><Pressable onPress={onBack} style={styles.icon}><ArrowLeft color={theme.ink} size={24}/></Pressable><Text style={[styles.headerTitle, {color: theme.ink}]}>Flow Library</Text><Pressable onPress={load} style={styles.icon}><RefreshCw color={theme.ink} size={19}/></Pressable></View>{loading ? <View style={styles.center}><ActivityIndicator size="large" color={theme.emerald}/></View> : <ScrollView contentContainerStyle={styles.page}><View style={styles.hero}><GitBranch color={theme.emerald} size={30}/><Text style={[styles.title, {color: theme.ink}]}>Project flows</Text><Text style={[styles.copy, {color: theme.muted}]}>Manage published and draft conversation flows.</Text></View><Pressable onPress={() => onOpenFlow()} style={[styles.newButton, {backgroundColor: theme.emerald}]}><Plus color="#FFF" size={18}/><Text style={styles.newText}>Create new flow</Text></Pressable>{groups.map(group => { const items = flows.filter(flow => flow.status === group); return <View key={group}><Text style={[styles.section, {color: theme.ink}]}>{group[0].toUpperCase() + group.slice(1)} ({items.length})</Text>{items.length === 0 ? <Text style={[styles.empty, {color: theme.muted}]}>No {group} flows.</Text> : items.map(flow => <View key={flow.flow_id} style={[styles.card, {backgroundColor: theme.surface, borderColor: theme.border}]}><View style={{flex: 1}}><Text style={[styles.cardTitle, {color: theme.ink}]}>{flow.name}</Text><Text style={[styles.copy, {color: theme.muted}]}>Version {flow.version}</Text>{activeId === flow.flow_id && <Text style={[styles.active, {color: theme.emerald}]}><Zap size={13}/> Active flow</Text>}</View><Pressable onPress={() => onOpenFlow(flow.flow_id)} style={styles.edit}><Edit3 color={theme.emerald} size={18}/></Pressable></View>)}</View>; })}</ScrollView>}</View>;
}
const styles = StyleSheet.create({safe: {flex: 1}, header: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1}, icon: {width: 40, height: 40, alignItems: 'center', justifyContent: 'center'}, headerTitle: {fontSize: 18, fontWeight: '800'}, center: {flex: 1, alignItems: 'center', justifyContent: 'center'}, page: {padding: 16, paddingBottom: 36}, hero: {alignItems: 'center', marginBottom: 18}, title: {fontSize: 22, fontWeight: '800', marginTop: 8}, copy: {fontSize: 13, lineHeight: 19, marginTop: 4}, newButton: {flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, padding: 13, borderRadius: 11, marginBottom: 16}, newText: {color: '#FFF', fontWeight: '800'}, section: {fontSize: 16, fontWeight: '800', marginTop: 13, marginBottom: 8}, empty: {fontSize: 13, marginBottom: 5}, card: {borderWidth: 1, borderRadius: 14, padding: 15, marginBottom: 9, flexDirection: 'row', alignItems: 'center'}, cardTitle: {fontSize: 15, fontWeight: '800'}, active: {fontSize: 12, fontWeight: '800', marginTop: 8}, edit: {padding: 10}});
