import React, {useCallback, useEffect, useState} from 'react';
import {ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View} from 'react-native';
import {ArrowLeft, Plus, Users} from 'lucide-react-native';
import Toast from 'react-native-toast-message';
import {ApiSession, post} from '../api/client';
import {FadeInView} from '../components/animations';
import {useTheme} from '../theme/theme';

type GroupsProps = {projectId: string; session: ApiSession; onBack: () => void; onOpen: (group: any) => void};

export function GroupsScreen({projectId, session, onBack, onOpen}: GroupsProps) {
  const theme = useTheme(); const [groups, setGroups] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [name, setName] = useState(''); const [remark, setRemark] = useState(''); const [showCreate, setShowCreate] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const res = await post<any>('/contact/group-list', {project_id: projectId, page_no: 1, page: 1, limit: 100}, session); setGroups(res?.data || res?.list || []); } catch (e: any) { Toast.show({type: 'error', text1: 'Could not load groups', text2: e?.message}); } finally { setLoading(false); } }, [projectId, session.token, session.username]);
  useEffect(() => { load(); }, [load]);
  const create = async () => { if (!name.trim()) return; try { const res = await post<any>('/contact/create-group', {project_id: projectId, name: name.trim(), remark: remark.trim()}, session); if (res?.error) throw new Error('Could not create group'); setName(''); setRemark(''); setShowCreate(false); load(); Toast.show({type: 'success', text1: 'Group created'}); } catch (e: any) { Toast.show({type: 'error', text1: 'Could not create group', text2: e?.message}); } };
  if (showCreate) return <FadeInView direction="right" distance={16} duration={260} style={styles.container}><View style={[styles.header, {backgroundColor: theme.header, borderBottomColor: theme.border}]}><Pressable onPress={() => setShowCreate(false)} style={styles.back}><ArrowLeft size={21} color={theme.ink}/></Pressable><View><Text style={[styles.title, {color: theme.ink}]}>Create Group</Text><Text style={[styles.subtitle, {color: theme.muted}]}>Add a new contact group</Text></View></View><View style={styles.createScreen}><Text style={[styles.createLabel, {color: theme.ink}]}>Group name</Text><TextInput autoFocus value={name} onChangeText={setName} placeholder="Enter group name" placeholderTextColor={theme.muted} style={[styles.input, {color: theme.ink, borderColor: theme.border, backgroundColor: theme.surface}]}/><Text style={[styles.createLabel, {color: theme.ink}]}>Remark</Text><TextInput value={remark} onChangeText={setRemark} placeholder="Enter remark (optional)" placeholderTextColor={theme.muted} multiline numberOfLines={3} textAlignVertical="top" style={[styles.remarkInput, {color: theme.ink, borderColor: theme.border, backgroundColor: theme.surface}]}/><Pressable onPress={create} style={[styles.createButton, {backgroundColor: theme.emerald}]}><Text style={styles.createButtonText}>Create group</Text></Pressable></View></FadeInView>;
  const renderGroup = ({item, index}: {item: any; index: number}) => <FadeInView delay={Math.min(index * 35, 250)} distance={12} duration={280}><Pressable onPress={() => onOpen(item)} style={[styles.card, {backgroundColor: theme.surface, borderColor: theme.border}]}><View style={[styles.icon, {backgroundColor: theme.mint}]}><Users size={18} color={theme.emerald}/></View><View style={{flex: 1}}><Text style={[styles.groupName, {color: theme.ink}]}>{item.name}</Text><Text style={[styles.count, {color: theme.muted}]}>{item.contact_count || item.count || 0} contacts</Text></View><Text style={{color: theme.emerald, fontSize: 22}}>›</Text></Pressable></FadeInView>;
  return <View style={[styles.container, {backgroundColor: theme.canvas}]}><View style={[styles.header, {backgroundColor: theme.header, borderBottomColor: theme.border}]}><Pressable onPress={onBack} style={styles.back}><ArrowLeft size={21} color={theme.ink}/></Pressable><View><Text style={[styles.title, {color: theme.ink}]}>Contact Groups</Text><Text style={[styles.subtitle, {color: theme.muted}]}>Tap a group to view its contacts</Text></View></View><FlatList data={groups} renderItem={renderGroup} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={{padding: 14, gap: 10, paddingBottom: 100}} keyExtractor={(item, index) => String(item.group_id || item.id || index)}/>{loading && !groups.length ? <ActivityIndicator color={theme.emerald}/> : null}<Pressable onPress={() => setShowCreate(true)} accessibilityRole="button" accessibilityLabel="Create group" style={[styles.fab, {backgroundColor: theme.emerald}]}><Plus size={24} color="#FFF"/></Pressable></View>;
}

const styles = StyleSheet.create({container: {flex: 1}, header: {padding: 16, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1}, back: {padding: 4, marginRight: 8}, title: {fontSize: 19, fontWeight: '800'}, subtitle: {fontSize: 11, marginTop: 2}, createScreen: {padding: 18, gap: 10}, createLabel: {fontSize: 13, fontWeight: '800'}, input: {height: 44, borderWidth: 1, borderRadius: 11, paddingHorizontal: 12}, remarkInput: {minHeight: 84, borderWidth: 1, borderRadius: 11, paddingHorizontal: 12, paddingTop: 12}, createButton: {height: 46, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginTop: 8}, createButtonText: {color: '#FFF', fontSize: 14, fontWeight: '800'}, fab: {position: 'absolute', bottom: 24, right: 24, width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', elevation: 4, shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 8, shadowOffset: {width: 0, height: 4}}, card: {borderWidth: 1, borderRadius: 14, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 10}, icon: {width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center'}, groupName: {fontSize: 14, fontWeight: '800'}, count: {fontSize: 12, marginTop: 3}});
