import React, {useCallback, useEffect, useState} from 'react';
import {ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View} from 'react-native';
import {ArrowLeft, Plus, Users} from 'lucide-react-native';
import Toast from 'react-native-toast-message';
import {ApiSession, post} from '../api/client';
import {useTheme} from '../theme/theme';

export function GroupsScreen({projectId, session, onBack, onOpen}: {projectId: string; session: ApiSession; onBack: () => void; onOpen: (group: any) => void}) {
  const theme = useTheme(); const [groups, setGroups] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [name, setName] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const res = await post<any>('/contact/group-list', {project_id: projectId, page_no: 1, page: 1, limit: 100}, session); setGroups(res?.data || res?.list || []); } catch (e: any) { Toast.show({type: 'error', text1: 'Could not load groups', text2: e?.message}); } finally { setLoading(false); } }, [projectId, session.token, session.username]);
  useEffect(() => { load(); }, [load]);
  const create = async () => { if (!name.trim()) return; try { const res = await post<any>('/contact/create-group', {project_id: projectId, name: name.trim(), remark: ''}, session); if (res?.error) throw new Error('Could not create group'); setName(''); load(); Toast.show({type: 'success', text1: 'Group created'}); } catch (e: any) { Toast.show({type: 'error', text1: 'Could not create group', text2: e?.message}); } };
  return <View style={[styles.container, {backgroundColor: theme.canvas}]}><View style={[styles.header, {backgroundColor: theme.header, borderBottomColor: theme.border}]}><Pressable onPress={onBack} style={styles.back}><ArrowLeft size={21} color={theme.ink}/></Pressable><View><Text style={[styles.title, {color: theme.ink}]}>Contact Groups</Text><Text style={[styles.subtitle, {color: theme.muted}]}>Tap a group to view its contacts</Text></View></View><View style={styles.createRow}><TextInput value={name} onChangeText={setName} placeholder="New group name" placeholderTextColor={theme.muted} style={[styles.input, {color: theme.ink, borderColor: theme.border}]}/><Pressable onPress={create} style={[styles.add, {backgroundColor: theme.emerald}]}><Plus size={17} color="#FFF"/></Pressable></View><FlatList data={groups} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={{padding: 14, gap: 10}} keyExtractor={(item, index) => String(item.group_id || item.id || index)} renderItem={({item}) => <Pressable onPress={() => onOpen(item)} style={[styles.card, {backgroundColor: theme.surface, borderColor: theme.border}]}><View style={[styles.icon, {backgroundColor: theme.mint}]}><Users size={18} color={theme.emerald}/></View><View style={{flex: 1}}><Text style={[styles.groupName, {color: theme.ink}]}>{item.name}</Text><Text style={[styles.count, {color: theme.muted}]}>{item.contact_count || item.count || 0} contacts</Text></View><Text style={{color: theme.emerald, fontSize: 22}}>›</Text></Pressable>}/>{loading && !groups.length ? <ActivityIndicator color={theme.emerald}/> : null}</View>;
}
const styles = StyleSheet.create({container: {flex: 1}, header: {padding: 16, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1}, back: {padding: 4, marginRight: 8}, title: {fontSize: 19, fontWeight: '800'}, subtitle: {fontSize: 11, marginTop: 2}, createRow: {padding: 14, flexDirection: 'row', gap: 8}, input: {flex: 1, height: 44, borderWidth: 1, borderRadius: 11, paddingHorizontal: 12}, add: {width: 44, borderRadius: 11, alignItems: 'center', justifyContent: 'center'}, card: {borderWidth: 1, borderRadius: 14, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 10}, icon: {width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center'}, groupName: {fontSize: 14, fontWeight: '800'}, count: {fontSize: 12, marginTop: 3}});
