import React, {useCallback, useEffect, useState} from 'react';
import {ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View} from 'react-native';
import {ArrowLeft, Search, Trash2, Users} from 'lucide-react-native';
import Toast from 'react-native-toast-message';
import {ApiSession} from '../api/client';
import {getGroupContacts, removeContactFromGroup} from '../api/workspace';
import {FadeInView} from '../components/animations';
import {useTheme} from '../theme/theme';

type GroupDetailsProps = {projectId: string; session: ApiSession; group: any; onBack: () => void};

export function GroupDetailsScreen({projectId, session, group, onBack}: GroupDetailsProps) {
  const theme = useTheme(); const groupId = String(group.group_id || group.id); const [contacts, setContacts] = useState<any[]>([]); const [total, setTotal] = useState(0); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(false); const [removing, setRemoving] = useState<string | number | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const response = await getGroupContacts(session, projectId, groupId, 1, 100, search); const list = response?.data || response?.list || []; setContacts(Array.isArray(list) ? list : []); setTotal(response?.meta?.total_records ?? response?.count ?? list.length); } catch (error: any) { Toast.show({type: 'error', text1: 'Could not load group contacts', text2: error?.message}); } finally { setLoading(false); } }, [groupId, projectId, search, session.token, session.username]);
  useEffect(() => { load(); }, [load]);
  const remove = async (contact: any) => { const id = contact.contact_id || contact.id; setRemoving(id); try { const response = await removeContactFromGroup(session, projectId, groupId, contact); if (response?.error) throw new Error('Remove failed'); Toast.show({type: 'success', text1: 'Contact removed from group'}); load(); } catch (error: any) { Toast.show({type: 'error', text1: 'Could not remove contact', text2: error?.message}); } finally { setRemoving(null); } };
  const renderContact = ({item, index}: {item: any; index: number}) => { const id = item.contact_id || item.id; return <FadeInView delay={Math.min(index * 35, 250)} distance={12} duration={280}><View style={[styles.card, {backgroundColor: theme.surface, borderColor: theme.border}]}><View style={[styles.avatar, {backgroundColor: theme.mint}]}><Text style={{color: theme.mintText, fontWeight: '900'}}>{(item.name || 'C').charAt(0).toUpperCase()}</Text></View><View style={{flex: 1}}><Text style={[styles.name, {color: theme.ink}]}>{item.name || 'Unnamed contact'}</Text><Text style={[styles.meta, {color: theme.muted}]}>{item.number || item.mobile || '-'}</Text>{item.email ? <Text style={[styles.meta, {color: theme.muted}]}>{item.email}</Text> : null}</View><Pressable onPress={() => remove(item)} disabled={removing === id} style={styles.delete}>{removing === id ? <ActivityIndicator size="small" color="#DC2626"/> : <Trash2 size={17} color="#DC2626"/>}</Pressable></View></FadeInView>; };
  return <View style={[styles.container, {backgroundColor: theme.canvas}]}><View style={[styles.header, {backgroundColor: theme.header, borderBottomColor: theme.border}]}><Pressable onPress={onBack} style={styles.back}><ArrowLeft size={21} color={theme.ink}/></Pressable><View style={{flex: 1}}><Text style={[styles.title, {color: theme.ink}]}>{group.name || 'Group details'}</Text><Text style={[styles.subtitle, {color: theme.muted}]}>{total} contact(s)</Text></View><View style={[styles.headerIcon, {backgroundColor: theme.mint}]}><Users size={19} color={theme.emerald}/></View></View><View style={[styles.search, {backgroundColor: theme.surface, borderColor: theme.border}]}><Search size={17} color={theme.muted}/><TextInput value={search} onChangeText={setSearch} placeholder="Search group contacts" placeholderTextColor={theme.muted} style={[styles.searchInput, {color: theme.ink}]}/></View><FlatList data={contacts} keyExtractor={(item, index) => String(item.unique_id || item.contact_id || item.id || index)} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={{padding: 14, gap: 10}} ListEmptyComponent={!loading ? <Text style={[styles.empty, {color: theme.muted}]}>No contacts in this group.</Text> : null} renderItem={renderContact}/></View>;
}

const styles = StyleSheet.create({container: {flex: 1}, header: {padding: 16, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1}, back: {padding: 4, marginRight: 9}, title: {fontSize: 19, fontWeight: '800'}, subtitle: {fontSize: 11, marginTop: 2}, headerIcon: {width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center'}, search: {margin: 14, height: 44, borderWidth: 1, borderRadius: 11, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 8}, searchInput: {flex: 1, fontSize: 14}, card: {padding: 13, borderWidth: 1, borderRadius: 14, flexDirection: 'row', alignItems: 'center', gap: 10}, avatar: {width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center'}, name: {fontSize: 14, fontWeight: '800'}, meta: {fontSize: 12, marginTop: 2}, delete: {padding: 10}, empty: {textAlign: 'center', padding: 40}});
