import React, {useCallback, useEffect, useMemo, useState} from 'react';
import {FlatList, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {ArrowLeft, Edit2, FileText, Plus, Trash2} from 'lucide-react-native';
import Toast from 'react-native-toast-message';
import {ApiSession} from '../api/client';
import {deleteTemplate, getTemplates, unwrapList} from '../api/workspace';
import {useTheme} from '../theme/theme';

export function TemplatesScreen({projectId, session, onBack, onCreate, onEdit}: {projectId: string; session: ApiSession; onBack: () => void; onCreate: () => void; onEdit: (template: any) => void}) {
  const theme = useTheme(); const [templates, setTemplates] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [search, setSearch] = useState(''); const [status, setStatus] = useState('ALL');
  const load = useCallback(async () => { setLoading(true); try { setTemplates(unwrapList(await getTemplates(session, projectId))); } catch (error: any) { Toast.show({type: 'error', text1: 'Could not load templates', text2: error?.message}); } finally { setLoading(false); } }, [projectId, session]);
  useEffect(() => { load(); }, [load]);
  const filtered = useMemo(() => templates.filter(item => { const name = item.template_name || item.name || ''; const itemStatus = item.status || item.template_status || ''; return name.toLowerCase().includes(search.toLowerCase()) && (status === 'ALL' || itemStatus === status); }), [templates, search, status]);
  const remove = async (item: any) => { try { const response = await deleteTemplate(session, projectId, item.template_id || item.id); if (response?.error) throw new Error('Delete failed'); Toast.show({type: 'success', text1: 'Template deleted'}); load(); } catch (error: any) { Toast.show({type: 'error', text1: 'Could not delete template', text2: error?.message}); } };
  return <View style={[styles.container, {backgroundColor: theme.canvas}]}><View style={[styles.header, {backgroundColor: theme.header, borderBottomColor: theme.border}]}><Pressable onPress={onBack} style={styles.back}><ArrowLeft size={21} color={theme.ink}/></Pressable><View style={{flex: 1}}><Text style={[styles.title, {color: theme.ink}]}>Templates</Text><Text style={[styles.subtitle, {color: theme.muted}]}>Manage WhatsApp message templates</Text></View></View><View style={styles.filters}><View style={[styles.searchBox, {borderColor: theme.border, backgroundColor: theme.surface}]}><FileText size={16} color={theme.muted}/><TextInput value={search} onChangeText={setSearch} placeholder="Search templates" placeholderTextColor={theme.muted} style={[styles.search, {color: theme.ink}]}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap: 8}}>{['ALL', 'PENDING', 'APPROVED', 'REJECTED'].map(item => <Pressable key={item} onPress={() => setStatus(item)} style={[styles.filter, {borderColor: theme.border, backgroundColor: status === item ? theme.emerald : theme.surface}]}><Text style={{color: status === item ? '#FFF' : theme.muted, fontSize: 11, fontWeight: '800'}}>{item}</Text></Pressable>)}</ScrollView></View><FlatList data={filtered} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={{padding: 14, gap: 10}} keyExtractor={(item, index) => String(item.template_id || item.id || index)} ListEmptyComponent={!loading ? <Text style={[styles.empty, {color: theme.muted}]}>No templates found.</Text> : null} renderItem={({item}) => <View style={[styles.card, {backgroundColor: theme.surface, borderColor: theme.border}]}><View style={[styles.icon, {backgroundColor: theme.mint}]}><FileText size={18} color={theme.emerald}/></View><View style={{flex: 1}}><Text style={[styles.name, {color: theme.ink}]}>{item.template_name || item.name}</Text><Text style={[styles.meta, {color: theme.muted}]}>{item.category || 'UTILITY'} Â· {item.language || item.language_code || 'en'}</Text><Text style={[styles.status, {color: theme.emerald}]}>{item.status || item.template_status || 'PENDING'}</Text></View><View style={styles.actions}><Pressable onPress={() => onEdit(item)} style={styles.action}><Edit2 size={16} color={theme.emerald}/></Pressable><Pressable onPress={() => remove(item)} style={styles.action}><Trash2 size={16} color="#DC2626"/></Pressable></View></View>}/><Pressable accessibilityRole="button" accessibilityLabel="Create template" onPress={onCreate} style={[styles.fab, {backgroundColor: theme.emerald}]}><Plus size={24} color="#FFF" strokeWidth={2.5}/></Pressable></View>;
}
const styles = StyleSheet.create({container: {flex: 1}, header: {padding: 16, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1}, back: {padding: 4, marginRight: 8}, title: {fontSize: 19, fontWeight: '800'}, subtitle: {fontSize: 11, marginTop: 2}, add: {width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center'}, fab: {position: 'absolute', right: 22, bottom: 24, width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', elevation: 5, shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 8, shadowOffset: {width: 0, height: 4}}, filters: {padding: 14, gap: 10}, searchBox: {height: 44, borderWidth: 1, borderRadius: 11, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 11, gap: 8}, search: {flex: 1, fontSize: 14}, filter: {paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1, borderRadius: 10}, card: {padding: 14, borderWidth: 1, borderRadius: 15, flexDirection: 'row', alignItems: 'center', gap: 10}, icon: {width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center'}, name: {fontSize: 14, fontWeight: '800'}, meta: {fontSize: 12, marginTop: 3}, status: {fontSize: 10, fontWeight: '800', marginTop: 4}, actions: {flexDirection: 'row', gap: 4}, action: {padding: 9}, empty: {textAlign: 'center', padding: 40}});


