import React, {useState} from 'react';
import {ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import { ArrowLeft, Sparkles } from 'lucide-react-native';
import { AiTemplateModal } from '../components/AiTemplateModal';
import Toast from 'react-native-toast-message';
import {ApiSession} from '../api/client';
import {createTemplate, editTemplate} from '../api/workspace';
import {useTheme} from '../theme/theme';

const CATEGORIES = ['MARKETING', 'UTILITY', 'AUTHENTICATION'];
const LANGUAGES = ['en', 'hi', 'es', 'fr', 'de', 'ar'];
const BUTTON_TYPES = ['NONE', 'QUICK_REPLY', 'PHONE_NUMBER', 'URL'];

function Picker({label, value, options, onChange, theme}: any) { const [open, setOpen] = useState(false); return <View><Text style={[styles.label, {color: theme.muted}]}>{label}</Text><Pressable onPress={() => setOpen(true)} style={[styles.select, {backgroundColor: theme.surface, borderColor: theme.border}]}><Text style={{color: theme.ink}}>{value}</Text><Text style={{color: theme.muted}}>⌄</Text></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}><Pressable style={styles.overlay} onPress={() => setOpen(false)}><View style={[styles.sheet, {backgroundColor: theme.surface}]}>{options.map((option: string) => <Pressable key={option} onPress={() => {onChange(option); setOpen(false);}} style={styles.option}><Text style={[styles.optionText, {color: theme.ink}]}>{option}</Text></Pressable>)}</View></Pressable></Modal></View>; }

function TemplatePreview({theme, header, body, footer, buttonType, buttonText}: any) { const sampleBody = (body || 'Your message preview will appear here.').replace(/{{\s*\d+\s*}}/g, 'John'); return <View style={[styles.previewCard, {backgroundColor: theme.surface, borderColor: theme.border}]}><Text style={[styles.previewTitle, {color: theme.ink}]}>Preview</Text><View style={styles.phone}><View style={styles.phoneTop}><Text style={styles.phoneTopText}>WhatsApp</Text></View><View style={styles.chat}><View style={styles.bubble}><Text style={styles.previewHeader}>{header || 'Template header'}</Text><Text style={styles.previewBody}>{sampleBody}</Text>{footer ? <Text style={styles.previewFooter}>{footer}</Text> : null}{buttonType !== 'NONE' && buttonText ? <View style={styles.previewButton}><Text style={styles.previewButtonText}>{buttonText}</Text></View> : null}</View><Text style={styles.previewTime}>10:32 AM ✓✓</Text></View></View></View>; }

export function TemplateEditorScreen({projectId, session, template, onBack, onSaved}: {projectId: string; session: ApiSession; template?: any; onBack: () => void; onSaved: () => void}) {
  const theme = useTheme(); const cs = template?.template?.components || template?.components || []; const get = (type: string) => cs.find((c: any) => c.type === type) || {}; const button = get('BUTTONS').buttons?.[0] || {};
  const [name, setName] = useState(template?.template_name || template?.name || ''); const [category, setCategory] = useState(template?.category || 'UTILITY'); const [language, setLanguage] = useState(template?.language || template?.language_code || 'en'); const [header, setHeader] = useState(get('HEADER').text || ''); const [body, setBody] = useState(get('BODY').text || ''); const [footer, setFooter] = useState(get('FOOTER').text || ''); const [buttonType, setButtonType] = useState(button.type || 'NONE'); const [buttonText, setButtonText] = useState(button.text || ''); const [buttonValue, setButtonValue] = useState(button.phone_number || button.url || ''); const [saving, setSaving] = useState(false);
  const [aiModalVisible, setAiModalVisible] = useState(false);

  const applyAiTemplate = (aiData: any) => {
    if (!aiData?.template) return;
    const t = aiData.template;
    const comps = t.components || [];
    const getComp = (type: string) => comps.find((c: any) => String(c.type).toUpperCase() === type) || {};
    const btnsComp = getComp('BUTTONS');
    const firstBtn = btnsComp?.buttons?.[0] || {};

    if (t.name) setName(t.name);
    if (t.category) setCategory(t.category);
    if (t.language) setLanguage(t.language);
    setHeader(getComp('HEADER').text || '');
    setBody(getComp('BODY').text || '');
    setFooter(getComp('FOOTER').text || '');
    setButtonType(firstBtn.type || 'NONE');
    setButtonText(firstBtn.text || '');
    setButtonValue(firstBtn.phone_number || firstBtn.url || '');
  };
  const field = (value: string, setValue: (value: string) => void, placeholder: string, multiline = false) => <TextInput value={value} onChangeText={setValue} multiline={multiline} placeholder={placeholder} placeholderTextColor={theme.muted} style={[multiline ? styles.textarea : styles.input, {color: theme.ink, borderColor: theme.border, backgroundColor: theme.surface}]}/>;
  const save = async () => { if (!name.trim() || !body.trim()) return Toast.show({type: 'error', text1: 'Name and body are required'}); if (buttonType !== 'NONE' && !buttonText.trim()) return Toast.show({type: 'error', text1: 'Button text is required'}); setSaving(true); try { const components: any[] = [{type: 'BODY', text: body.trim()}]; if (header.trim()) components.unshift({type: 'HEADER', format: 'TEXT', text: header.trim()}); if (footer.trim()) components.push({type: 'FOOTER', text: footer.trim()}); if (buttonType !== 'NONE') { const b: any = {type: buttonType, text: buttonText.trim()}; if (buttonType === 'PHONE_NUMBER') b.phone_number = buttonValue.trim(); if (buttonType === 'URL') b.url = buttonValue.trim(); components.push({type: 'BUTTONS', buttons: [b]}); } const payload = {name: name.trim().toLowerCase().replace(/\s+/g, '_'), category, language, components}; const response = template ? await editTemplate(session, projectId, template.template_id || template.id, payload) : await createTemplate(session, projectId, payload); if (response?.error) throw new Error('Template save failed'); Toast.show({type: 'success', text1: template ? 'Template updated' : 'Template created'}); onSaved(); } catch (error: any) { Toast.show({type: 'error', text1: 'Could not save template', text2: error?.message}); } finally { setSaving(false); } };
  return <View style={[styles.container, {backgroundColor: theme.canvas}]}><View style={[styles.header, {backgroundColor: theme.header, borderBottomColor: theme.border}]}><Pressable onPress={onBack} style={styles.back}><ArrowLeft size={21} color={theme.ink}/></Pressable><View><Text style={[styles.title, {color: theme.ink}]}>{template ? 'Edit Template' : 'Create Template'}</Text><Text style={[styles.subtitle, {color: theme.muted}]}>WhatsApp message template</Text></View></View><ScrollView contentContainerStyle={styles.form}><Pressable onPress={() => setAiModalVisible(true)} style={[styles.aiBanner, {backgroundColor: theme.emerald + '15', borderColor: theme.emerald}]}>
      <View style={{flexDirection: 'row', alignItems: 'center', gap: 8}}>
        <Sparkles size={16} color={theme.emerald}/>
        <Text style={[styles.aiBannerText, {color: theme.emerald}]}>Generate with AI Assistant</Text>
      </View>
      <Text style={[styles.aiBannerSub, {color: theme.emerald}]}>Auto-fill</Text>
    </Pressable>
    <TemplatePreview theme={theme} header={header} body={body} footer={footer} buttonType={buttonType} buttonText={buttonText}/><Text style={[styles.sectionTitle, {color: theme.ink}]}>Template details</Text><Text style={[styles.label, {color: theme.muted}]}>Template name *</Text>{field(name, setName, 'order_update')}<Picker label="Category" value={category} options={CATEGORIES} onChange={setCategory} theme={theme}/><Picker label="Language" value={language} options={LANGUAGES} onChange={setLanguage} theme={theme}/><Text style={[styles.label, {color: theme.muted}]}>Header text</Text>{field(header, setHeader, 'Optional header')}<Text style={[styles.label, {color: theme.muted}]}>Body *</Text>{field(body, setBody, 'Hello {{1}}', true)}<Text style={[styles.label, {color: theme.muted}]}>Footer text</Text>{field(footer, setFooter, 'Optional footer')}<Picker label="Button" value={buttonType} options={BUTTON_TYPES} onChange={setButtonType} theme={theme}/>{buttonType !== 'NONE' && <><Text style={[styles.label, {color: theme.muted}]}>Button text *</Text>{field(buttonText, setButtonText, 'Learn more')}{buttonType !== 'QUICK_REPLY' && <><Text style={[styles.label, {color: theme.muted}]}>{buttonType === 'URL' ? 'Button URL' : 'Phone number'}</Text>{field(buttonValue, setButtonValue, buttonType === 'URL' ? 'https://example.com' : '+919999999999')}</>}</>}<Pressable onPress={save} disabled={saving} style={[styles.save, {backgroundColor: theme.emerald}]}>{saving ? <ActivityIndicator color="#FFF"/> : <Text style={styles.saveText}>{template ? 'Save changes' : 'Create template'}</Text>}</Pressable><AiTemplateModal visible={aiModalVisible} onClose={() => setAiModalVisible(false)} session={session} projectId={projectId} onApplyTemplate={applyAiTemplate} onSavedDirectly={onSaved}/>
    </ScrollView></View>;
}

const styles = StyleSheet.create({container: {flex: 1}, header: {padding: 16, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1}, back: {padding: 4, marginRight: 10}, title: {fontSize: 19, fontWeight: '800'}, subtitle: {fontSize: 11, marginTop: 2}, form: {padding: 17, gap: 10}, sectionTitle: {fontSize: 16, fontWeight: '900', marginTop: 2}, label: {fontSize: 11, fontWeight: '800', marginTop: 4}, input: {height: 46, borderWidth: 1, borderRadius: 11, paddingHorizontal: 12, fontSize: 14}, textarea: {minHeight: 120, borderWidth: 1, borderRadius: 11, padding: 12, fontSize: 14, textAlignVertical: 'top'}, select: {height: 46, borderWidth: 1, borderRadius: 11, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'}, overlay: {flex: 1, backgroundColor: 'rgba(0,0,0,.45)', justifyContent: 'flex-end'}, sheet: {padding: 18, borderTopLeftRadius: 22, borderTopRightRadius: 22}, option: {paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#E5E7EB'}, optionText: {fontSize: 14, fontWeight: '700'}, save: {paddingVertical: 15, borderRadius: 11, alignItems: 'center', marginTop: 10}, saveText: {color: '#FFF', fontWeight: '800'}, aiBanner: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 12, borderRadius: 12, borderWidth: 1, marginBottom: 4}, aiBannerText: {fontSize: 13, fontWeight: '900'}, aiBannerSub: {fontSize: 11, fontWeight: '800'}, previewCard: {borderWidth: 1, borderRadius: 16, padding: 12, marginBottom: 3}, previewTitle: {fontSize: 14, fontWeight: '900', marginBottom: 9}, phone: {borderRadius: 15, overflow: 'hidden', backgroundColor: '#E6DDD5', maxWidth: 360, alignSelf: 'center', width: '100%'}, phoneTop: {backgroundColor: '#075E54', paddingVertical: 9, paddingHorizontal: 12}, phoneTopText: {color: '#FFF', fontSize: 12, fontWeight: '800'}, chat: {padding: 13, minHeight: 155, justifyContent: 'flex-end'}, bubble: {backgroundColor: '#FFF', borderRadius: 10, borderTopLeftRadius: 3, padding: 10, alignSelf: 'flex-start', maxWidth: '94%', shadowColor: '#000', shadowOpacity: .08, shadowRadius: 3, elevation: 1}, previewHeader: {fontWeight: '900', color: '#111827', fontSize: 13}, previewBody: {color: '#1F2937', fontSize: 13, lineHeight: 18, marginTop: 5}, previewFooter: {color: '#6B7280', fontSize: 11, marginTop: 7}, previewButton: {borderTopWidth: 1, borderTopColor: '#E5E7EB', marginTop: 9, paddingTop: 8}, previewButtonText: {color: '#128C7E', textAlign: 'center', fontWeight: '800', fontSize: 12}, previewTime: {color: '#6B7280', fontSize: 9, alignSelf: 'flex-end', marginTop: 4}});
