import React, {useCallback, useEffect, useState} from 'react';
import {FlatList, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {getCampaigns, getContacts, getInbox, getProjectInfo, getTemplates, ListItem, unwrapList} from '../api/workspace';
import {Session} from '../services/session';
import {LoadState} from '../components/LoadState';
import {colors, ui} from '../theme/theme';

type Tab = 'Inbox' | 'Campaigns' | 'Contacts' | 'Templates' | 'More';
const tabs: Tab[] = ['Inbox', 'Campaigns', 'Contacts', 'Templates', 'More'];
const nameOf = (item: ListItem) => String(item.name || item.contact_name || item.template_name || item.campaign_name || item.phone || 'Untitled');
const detailOf = (item: ListItem) => String(item.message || item.status || item.category || item.phone || item.email || '');

export function WorkspaceScreen({session, onSignOut}: {session: Session; onSignOut: () => void}) {
  const [tab, setTab] = useState<Tab>('Inbox'); const [projectId, setProjectId] = useState(session.projects[0]?.id || ''); const [items, setItems] = useState<ListItem[]>([]); const [info, setInfo] = useState<any>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => {
    if (!projectId) return; setLoading(true); setError('');
    try { const request = tab === 'Inbox' ? getInbox : tab === 'Campaigns' ? getCampaigns : tab === 'Contacts' ? getContacts : tab === 'Templates' ? getTemplates : getProjectInfo; const result = await request({token: session.token, username: session.username}, projectId); if (tab === 'More') setInfo(result); else setItems(unwrapList(result)); }
    catch (e) { setItems([]); setError(e instanceof Error ? e.message : 'Could not load this data.'); }
    finally { setLoading(false); }
  }, [projectId, session.token, session.username, tab]);
  useEffect(() => {load();}, [load]);
  const title = tab === 'More' ? 'Workspace' : tab;
  if (!projectId) return <SafeAreaView style={ui.screen}><View style={styles.noProject}><Text style={ui.title}>No workspace found</Text><Text style={[ui.subtitle, {textAlign:'center'}]}>Your account has no available projects. Contact your administrator or try signing in again.</Text><Pressable onPress={onSignOut} style={[ui.button, {marginTop:22,width:160}]}><Text style={ui.buttonText}>Sign out</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={ui.screen} edges={['top']}><View style={styles.header}><View><Text style={styles.workspace}>{session.projects.find(p => p.id === projectId)?.name || 'Workspace'}</Text><Text style={styles.online}>Live server data</Text></View><Pressable onPress={() => {const next = session.projects.find(p => p.id !== projectId); if (next) setProjectId(next.id);}}><Text style={styles.switch}>Switch</Text></Pressable></View><View style={styles.content}><Text style={ui.title}>{title}</Text><Text style={ui.subtitle}>{tab === 'More' ? 'Project balance and configuration' : `Current ${title.toLowerCase()} from your project`}</Text>{tab === 'More' ? <ProjectInfo info={info} loading={loading} error={error} reload={load} onSignOut={onSignOut} /> : <DataList items={items} loading={loading} error={error} reload={load} />}</View><View style={styles.tabs}>{tabs.map(x => <Pressable key={x} onPress={() => setTab(x)} style={styles.tab}><Text style={[styles.tabText, tab === x && styles.activeTab]}>{x}</Text></Pressable>)}</View></SafeAreaView>;
}
function DataList({items, loading, error, reload}: {items: ListItem[]; loading: boolean; error: string; reload: () => void}) {return <FlatList data={items} keyExtractor={(x,i) => String(x.id || x._id || i)} refreshControl={<RefreshControl refreshing={loading} onRefresh={reload} tintColor={colors.emerald} />} ListEmptyComponent={<LoadState loading={loading} error={error} empty={!loading && !error} onRetry={reload} />} contentContainerStyle={items.length ? styles.list : styles.emptyList} renderItem={({item}) => <View style={ui.card}><Text style={styles.itemName}>{nameOf(item)}</Text><Text numberOfLines={2} style={styles.itemDetail}>{detailOf(item)}</Text></View>} />}
function ProjectInfo({info, loading, error, reload, onSignOut}: {info:any;loading:boolean;error:string;reload:()=>void;onSignOut:()=>void}) {const value = info?.data || info || {}; return <ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={reload} />}><LoadState loading={loading} error={error} empty={!loading && !error && !info} onRetry={reload} />{info && <><View style={ui.card}><Text style={ui.label}>WALLET BALANCE</Text><Text style={styles.balance}>₹ {String(value.wallet_balance || value.balance || '0')}</Text></View><View style={ui.card}><Text style={styles.itemName}>{String(value.project_name || value.name || 'Project details')}</Text><Text style={styles.itemDetail}>{String(value.waba_name || value.waba_id || 'Business configuration loaded from the server')}</Text></View></>}<Pressable onPress={onSignOut} style={styles.signOut}><Text style={styles.signOutText}>Sign out</Text></Pressable></ScrollView>}
const styles = StyleSheet.create({header:{height:69,paddingHorizontal:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:1,borderColor:colors.border},workspace:{fontSize:14,fontWeight:'800',color:colors.ink},online:{fontSize:10,color:colors.emerald,marginTop:3},switch:{fontSize:12,fontWeight:'800',color:colors.emerald},content:{flex:1,paddingHorizontal:20,paddingTop:18},tabs:{height:70,backgroundColor:'#FFF',borderTopWidth:1,borderColor:colors.border,flexDirection:'row',justifyContent:'space-around',alignItems:'center'},tab:{height:50,justifyContent:'center',paddingHorizontal:4},tabText:{fontSize:10,color:colors.muted,fontWeight:'700'},activeTab:{color:colors.emerald},list:{paddingTop:7,paddingBottom:14},emptyList:{flexGrow:1,justifyContent:'center'},itemName:{fontSize:15,fontWeight:'800',color:colors.ink},itemDetail:{fontSize:12,color:colors.muted,lineHeight:18,marginTop:6},balance:{fontSize:26,fontWeight:'800',color:colors.ink,marginTop:8},noProject:{flex:1,alignItems:'center',justifyContent:'center',padding:28},signOut:{alignItems:'center',padding:20},signOutText:{color:colors.danger,fontWeight:'800',fontSize:13}});
